system:
  app-id: ZMQ
  port:
    quote: 51237
  service-key: 8076c9867a372d2a9a814ae710c256e2

log:
  suppress-warnings: false

data:
  stream:
    timeout-sec: 300
    px-update-sec: 2
    px-update-offset-sec: 0.25
    px-update-market-sec: 0.1
  source:
    - type: Futures
      exchange: CME
      symbol: NQ
      expiry: HOT
    - type: Futures
      exchange: CBOT
      symbol: YM
      expiry: HOT
    - type: Futures
      exchange: TWF
      symbol: FITX
      expiry: HOT
  sr-level:
    custom: {}

indicator:
  ema-net:
    fast: 10
    slow: 34
  ema-strong-sr:
    - fast: 144
      slow: 169
    - fast: 576
      slow: 676
  sr-level:
    min-diff: 35

account:
  sign-up-key-expiry-sec: 86400
