system:
  app-id: ZMQ
  port:
    quote: 51237
  service-key: 8076c9867a372d2a9a814ae710c256e2

log:
  suppress-warnings: false

data:
  stream:
    timeout-sec: 300
    px-update-sec: 2
    px-update-market-sec: 0.2
  source:
    - type: Futures
      exchange: CME
      symbol: NQ
      expiry: HOT
    - type: Futures
      exchange: CBOT
      symbol: YM
      expiry: HOT
    - type: Futures
      exchange: TWF
      symbol: FITX
      expiry: HOT
  sr-level:
    strong-threshold: 0.6
    custom:
      FITX:
        - level: 16303
        - level: 16320
        - level: 16356
        - level: 16400
        - level: 16461
        - level: 16505
        - level: 16620
          strong: true
