system:
  app-id: ZMQ
  port:
    quote: 51237
  service-key: 8076c9867a372d2a9a814ae710c256e2

log:
  suppress-warnings: false

data:
  stream:
    timeout-secs: 300
  source:
    - type: Futures
      exchange: TWF
      symbol: FITX
      expiry: HOT
    - type: Futures
      exchange: CBOT
      symbol: YM
      expiry: HOT
    - type: Futures
      exchange: CME
      symbol: NQ
      expiry: HOT
