system:
  app-id: ZMQ
  port:
    quote: 51237
  service-key: 8076c9867a372d2a9a814ae710c256e2

log:
  suppress-warnings: false

data:
  download:
    1k: 240
    dk: 1800
  stream:
    segment-count: 2000
    timeout-sec: 300
    px-update:
      market-time-gate-sec: 0.075
    px-history-refetch:
      interval-sec: 10
      backward-hour: 1
  source:
    - type: Futures
      type-market-date: US Index Futures
      exchange: CME
      symbol: NQ
      expiry: HOT
      name: 小那指
      session:
        - weekdays: [6, 0, 1, 2, 3]
          start: '22:00'
          end: '21:00'
    - type: Futures
      type-market-date: US Index Futures
      exchange: CBOT
      symbol: YM
      expiry: HOT
      name: 小道瓊
      session:
        - weekdays: [6, 0, 1, 2, 3]
          start: '22:00'
          end: '21:00'
    - type: Futures
      type-market-date: FITX
      exchange: TWF
      symbol: FITX
      expiry: HOT
      name: 台指期
      session:
        - weekdays: [0, 1, 2, 3, 4]
          start: '00:45'
          end: '05:45'
        - weekdays: [0, 1, 2, 3, 4]
          start: '07:00'
          end: '21:00'
  period:
    min:
      - min: 1
        name: '1'
      - min: 3
        name: '3'
      - min: 5
        name: '5'
      - min: 10
        name: '10'
      - min: 15
        name: '15'
      - min: 30
        name: '30'
      - min: 60
        name: '60'
    day: []
  sr-level:
    custom: {}

indicator:
  ema-net:
    fast: 10
    slow: 34
  ema-strong-sr:
    - fast: 144
      slow: 169
    - fast: 576
      slow: 676
  sr-level:
    min-diff: 35

account:
  sign-up-key-expiry-sec: 86400
  token-auto-refresh-leeway-sec: 86400
