system:
  touchance:
    app-id: ZMQ
    port:
      quote: 51237
    service-key: 8076c9867a372d2a9a814ae710c256e2
  grpc:
    px-calc: localhost:5098

log:
  suppress-warnings: false

data:
  download:
    1k: 240
    dk: 1800
  cache:
    px-request-ttl-sec: 1
    px-request-ttl-size: 15
  stream:
    segment-count: 2000
    timeout-sec: 300
    px-update:
      market-time-gate-sec: 0.1
      market-delay-warning-sec: 2
    px-history-refetch:
      limit: 50
      backward-hour: 2
  source:
    - type: Futures
      type-market-date: US Index Futures
      exchange: CME
      symbol: ES
      expiry: HOT
      name: SP 500
      session:
        - weekdays: [6, 0, 1, 2, 3]
          start: '23:00'
          end: '22:00'
      sr-level:
        group:
          open: '14:30'
          close: '21:00'
    - type: Futures
      type-market-date: US Index Futures
      exchange: CME
      symbol: NQ
      expiry: HOT
      name: 小那指
      session:
        - weekdays: [6, 0, 1, 2, 3]
          start: '23:00'
          end: '22:00'
      sr-level:
        group:
          open: '14:30'
          close: '21:00'
    - type: Futures
      type-market-date: US Index Futures
      exchange: CBOT
      symbol: YM
      expiry: HOT
      name: 小道瓊
      session:
        - weekdays: [6, 0, 1, 2, 3]
          start: '23:00'
          end: '22:00'
      sr-level:
        group:
          open: '14:30'
          close: '21:00'
    - type: Futures
      type-market-date: FITX
      exchange: TWF
      symbol: FITX
      expiry: HOT
      name: 台指期
      session:
        - weekdays: [0, 1, 2, 3, 4]
          start: '00:45'
          end: '05:45'
        - weekdays: [0, 1, 2, 3, 4]
          start: '07:00'
          end: '21:00'
      sr-level:
        group:
          open: '00:45'
          close: '05:30'
        basic:
          open: '07:00'
          close: '05:30'
  sr-level:
    custom: {}

account:
  sign-up-key-expiry-sec: 86400
  token-auto-refresh-leeway-sec: 86400
