# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kl_site_proto/pxData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1akl_site_proto/pxData.proto\x12\x06KLSite\"%\n\x13PxCalcRequestSingle\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"%\n\x12PxCalcRequestMulti\x12\x0f\n\x07symbols\x18\x01 \x03(\t\"\x1e\n\x0bPxCalcReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xc2\x01\n\x06PxData\x12:\n\x07\x43\x61lcAll\x12\x1a.KLSite.PxCalcRequestMulti\x1a\x13.KLSite.PxCalcReply\x12>\n\x0b\x43\x61lcPartial\x12\x1a.KLSite.PxCalcRequestMulti\x1a\x13.KLSite.PxCalcReply\x12<\n\x08\x43\x61lcLast\x12\x1b.KLSite.PxCalcRequestSingle\x1a\x13.KLSite.PxCalcReplyB\r\xaa\x02\nKLSiteCalcb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kl_site_proto.pxData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\nKLSiteCalc'
  _PXCALCREQUESTSINGLE._serialized_start=38
  _PXCALCREQUESTSINGLE._serialized_end=75
  _PXCALCREQUESTMULTI._serialized_start=77
  _PXCALCREQUESTMULTI._serialized_end=114
  _PXCALCREPLY._serialized_start=116
  _PXCALCREPLY._serialized_end=146
  _PXDATA._serialized_start=149
  _PXDATA._serialized_end=343
# @@protoc_insertion_point(module_scope)
