from datetime import timedelta

from kl_site_common.const import INDICATOR_EMA_PERIODS

CANDLESTICK_DIR_MACD_FAST = 20

CANDLESTICK_DIR_MACD_SIGNAL = 15

CANDLESTICK_DIR_MACD_SLOW = 300

CANDLESTICK_DIR_MACD_REQUIRED = CANDLESTICK_DIR_MACD_SIGNAL + CANDLESTICK_DIR_MACD_SLOW

_PERIODS_NO_EMA = [CANDLESTICK_DIR_MACD_REQUIRED, CANDLESTICK_DIR_MACD_FAST]

MAX_PERIOD = max(*INDICATOR_EMA_PERIODS, *_PERIODS_NO_EMA)

MAX_PERIOD_NO_EMA = max(*_PERIODS_NO_EMA)


def get_start_offset(period_min: int) -> timedelta:
    return timedelta(minutes=period_min * MAX_PERIOD)
