pool:
  vmImage: windows-latest

variables:
  - template: variables/main.yml
  - template: variables/checkout-and-cache.yml

trigger:
  - main
  - dev

stages:
- stage: Lint

  jobs:
    - job: Lint

      steps:
      - template: templates/checkout-and-cache.yml

      - displayName: 'Install flake8'
        script: pip install flake8

      - displayName: 'Run flake8'
        script: flake8

- stage: Deploy

  dependsOn:
    - Lint

  jobs:
    - job: Deploy

      steps:
        - template: templates/checkout-and-cache.yml

        - task: Cache@2
          displayName: 'Cache Built Source'
          inputs:
            key: 'build | "$(Agent.OS)" | "$(Build.BuildNumber)"'
            path: '$(Pipeline.Workspace)/s'

        - task: ArchiveFiles@2
          displayName: 'Archive Build Artifacts'

          inputs:
            rootFolderOrFile: '.'
            includeRootFolder: false
            archiveType: 'tar'
            archiveFile: '$(Build.ArtifactStagingDirectory)/kl-site-back.tar.gz'
            replaceExistingArchive: true

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Build Artifacts'

          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/kl-site-back.tar.gz'
            ArtifactName: 'kl-site-back-artifact'
            publishLocation: 'Container'
