pool:
  vmImage: windows-latest

variables:
  - template: variables/main.yml
  - template: variables/checkout-and-cache.yml

trigger:
  - main
  - dev

stages:
- stage: Lint

  jobs:
    - job: Lint

      steps:
      - template: templates/checkout-and-cache.yml

      - displayName: 'Install flake8'
        script: pip install flake8

      - displayName: 'Run flake8'
        script: flake8
