pool:
  vmImage: windows-latest

variables:
  - template: variables/main.yml
  - template: variables/checkout-and-cache.yml

trigger:
  - main
  - dev

stages:
  - stage: CQ
    displayName: 'Code Quality Check'
    jobs:
      - job: Lint
        steps:
        - template: templates/checkout-and-cache.yml

        - script: pip install flake8
          displayName: 'Install flake8'

        - script: flake8
          displayName: 'Run flake8'

      - job: Test
        steps:
        - template: templates/checkout-and-cache.yml

        - script: choco install mongodb
          displayName: 'Install MongoDB'

        - script: pip install pytest
          displayName: 'Install pytest'

        - script: pytest
          displayName: 'Run pytest'
          env:
            FASTAPI_AUTH_CALLBACK: $(variables.FASTAPI_AUTH_CALLBACK)
            FASTAPI_AUTH_SECRET: $(variables.FASTAPI_AUTH_SECRET)
            MONGO_URL: $(variables.MONGO_URL)

  - stage: Deploy
    dependsOn:
      - CQ
    jobs:
      - job: Deploy

        steps:
          - template: templates/checkout-and-cache.yml

          - task: Cache@2
            displayName: 'Cache Built Source'
            inputs:
              key: 'build | "$(Agent.OS)" | "$(Build.BuildNumber)"'
              path: '$(Pipeline.Workspace)/s'

          - task: ArchiveFiles@2
            displayName: 'Archive Build Artifacts'

            inputs:
              rootFolderOrFile: '.'
              includeRootFolder: false
              archiveType: 'tar'
              archiveFile: '$(Build.ArtifactStagingDirectory)/kl-site-back.tar.gz'
              replaceExistingArchive: true

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Build Artifacts'

            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/kl-site-back.tar.gz'
              ArtifactName: 'kl-site-back-artifact'
              publishLocation: 'Container'
